### PR TITLE
Use bundle exec middleman.

### PR DESCRIPTION
**Pull request by linjunpop**

### CODE REVIEW

**Comment by hovancik** [comment]
Thanks for the contribution. 

What's the motivation to add `bundle exec`? Do you have some issues that it solves? 
Anyway, right now the tests are failing, will need to find time to check what's happening there.

**Comment by linjunpop** [comment]
Because I got errors if not using bundle:

```
WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Users/jun/.asdf/installs/ruby/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:40:in `block in setup': You have already activated tilt 2.0.7, but your Gemfile requires tilt 1.4.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /Users/jun/.asdf/installs/ruby/2.3.4/lib/ruby/2.3.0/forwardable.rb:204:in `each'
	from /Users/jun/.asdf/installs/ruby/2.3.4/lib/ruby/2.3.0/forwardable.rb:204:in `each'
	from /Users/jun/.asdf/installs/ruby/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:25:in `map'
	from /Users/jun/.asdf/installs/ruby/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:25:in `setup'
	from /Users/jun/.asdf/installs/ruby/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
	from /Users/jun/.asdf/installs/ruby/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/setup.rb:10:in `<top (required)>'
	from /Users/jun/.asdf/installs/ruby/2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/jun/.asdf/installs/ruby/2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/jun/.asdf/installs/ruby/2.3.4/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/load_paths.rb:34:in `setup_bundler'
	from /Users/jun/.asdf/installs/ruby/2.3.4/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
	from /Users/jun/.asdf/installs/ruby/2.3.4/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/bin/middleman:10:in `<top (required)>'
	from /Users/jun/.asdf/installs/ruby/2.3.4/bin/middleman:22:in `load'
	from /Users/jun/.asdf/installs/ruby/2.3.4/bin/middleman:22:in `<main>'
```

And I guess use `bundle exec` should be a good way.

**Comment by hovancik** [comment]
Thanks, I see. 

So you run `mgd` ? What happens when you run `bundle exec mgd` ? 
I also wonder what is your environment and how do you install ruby? Maybe I can reproduce the issue.

**Comment by linjunpop** [comment]
Hmm. I'm using binstubs `mgd`, but I cannot reproduce this error anymore.

So I gonna close this, if it happens again, I will reopen it.

**Comment by hovancik** [comment]
ok.

**Pull request closed without merging**
