### PR TITLE
first release

### PR DESCRIPTION
**Pull request by hovancik**
get ready for first release

### CODE REVIEW

**Comment by hovancik** [comment]
@rultor release please, tag is 0.1.0

**Comment by hovancik** [comment]
@rultor release, tag=`0.1.0`

**Comment by hovancik** [comment]
@rultor release, tag=`0.1.0`

**Comment by hovancik** [comment]
@rultor status

**Comment by hovancik** [comment]
@rultor stop

**Comment by hovancik** [comment]
@rultor status

**Comment by yegor256** [comment]
@hovancik you have to put tag name in backticks, as in this example: http://doc.rultor.com/basics.html

**Comment by hovancik** [comment]
@yegor256 I've tried in https://github.com/hovancik/middleman-github-deploy/pull/2 but there was error. not sure what the workflow to fix this would be, doing another PR and trying something seems overkill

**Comment by yegor256** [comment]
@hovancik there is another problem in #2, I just posted a comment there

**Pull request merged**
